FROM python:3.11-slim

WORKDIR /app

# Копируем requirements из папки backend
COPY backend/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем весь код бэкенда
COPY backend/ .

# Создаем папки для статики
RUN mkdir -p static/avatars static/posts

EXPOSE 8000

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]